apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: kafka
  labels:
    strimzi.io/cluster: rambo-kraft-cluster
spec:
  replicas: 1
  roles:
    - controller
    - broker
  resources:
    requests:
      memory: 1Gi
      cpu: "250m"
    limits:
      memory: 2Gi
      cpu: "500m"
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        class: standard
        size: 100Gi
        deleteClaim: false
        kraftMetadata: shared

---

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: rambo-kraft-cluster
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.8.0
    metadataVersion: 3.8-IV0
    listeners:
      - name: plain
        port: 9092
        type: loadbalancer
        tls: false
        configuration:
          loadBalancerSourceRanges:
            - 0.0.0.0/0  # Allow access from anywhere, adjust as necessary
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1     
  entityOperator:
    topicOperator:
      resources:
          requests:
            memory: 1Gi
            cpu: "250m"
          limits:
            memory: 2Gi
            cpu: "500m"
    userOperator: {}
