substitutions:
  _USER: "Rahul"

steps:
  # Step 1: Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://github.com/rahulrambo9/tic-tac-toe-with-kafka-mongodb.git
        cd tic-tac-toe-with-kafka-mongodb/tic-tac-toe
        echo "Repository cloned and navigated to subdirectory."

  # Step 2: Read the current version from version.txt and increment it
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd tic-tac-toe-with-kafka-mongodb/tic-tac-toe
        if [ -f version.txt ]; then
          # Read the current version, ensure it starts with 'v'
          _CURRENT_VERSION=$(cat version.txt | sed 's/^v//')
          echo "Current version in version.txt: v$_CURRENT_VERSION"
        
          # Validate if _CURRENT_VERSION is a valid number
          if [[ $_CURRENT_VERSION =~ ^[0-9]+$ ]]; then
            # Increment the version
            _NEW_VERSION=$(( _CURRENT_VERSION + 1 ))
            echo "Updated version: v$_NEW_VERSION"
            # Write the new version back to version.txt with 'v' prefix
            echo "v$_NEW_VERSION" > version.txt  
          else
            echo "Error: Current version is not a valid number"
            exit 1
          fi
        else
          echo "version.txt not found!"
          exit 1
        fi

  # Step 3: Output the incremented version
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd tic-tac-toe-with-kafka-mongodb/tic-tac-toe
        echo "Hello ${_USER}"
        echo "Your new TagName is v$_NEW_VERSION"

options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY  # Use this logging option to avoid the error

# Optional: Specify a timeout
timeout: '1200s'  # Adjust the timeout as needed
