substitutions:
  _USER: "Rahul"
  _TAG_NAME: "v1"  # Set your actual project ID here

steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Hello ${_USER}"
  
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Your TagName is ${_TAG_NAME}"

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git config --global user.email "rahulvhd9@gmail.com"
        git config --global user.name "rahulrambo9"
        git clone https://github.com/rahulrambo9/tic-tac-toe-with-kafka-mongodb.git
        cd tic-tac-toe

    # Step 2: Read, increment, and display the version from version.txt
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export _TAG_VERSION=$(($(cat version.txt) + 1))
        echo "${_TAG_VERSION}" > version.txt
        echo "Hello ${_USER}"
        echo "Your new TagName is v${_TAG_VERSION}"

  # Step 3: Commit and push the updated version.txt back to the repository
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd tic-tac-toe
        git add version.txt
        git commit -m "Increment version to v${_TAG_VERSION}"
        git push origin main  # Make sure your branch name is correct   

options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY  # Use this logging option to avoid the error

# Optional: Specify a timeout
timeout: '1200s'  # Adjust the timeout as needed
