substitutions:
  _USER: "Rahul"
  _TAG_NAME: "v1"

steps:
  # Step 1: Clone the Repository
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://github.com/rahulrambo9/tic-tac-toe-with-kafka-mongodb.git
        cd tic-tac-toe-with-kafka-mongodb/tic-tac-toe
        echo "Repository cloned and navigated to subdirectory."

  # Step 2: Read, Increment, and Display the Version from version.txt
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd tic-tac-toe-with-kafka-mongodb/tic-tac-toe
        
        # Check if version.txt exists; if not, initialize it with v1
        if [ ! -f version.txt ]; then 
          echo "v1" > version.txt  
          echo "Initialized version.txt with v1."
        fi

        # Read the current version (remove "v" to get the number)
        CURRENT_VERSION=$(cat version.txt | sed 's/v//')  
        echo "Current version in version.txt: v${CURRENT_VERSION}"

        # Increment the version number
        NEW_VERSION=$((CURRENT_VERSION + 1))  
        echo "New version calculated: v${NEW_VERSION}"

        # Write the new version back to version.txt
        echo "v${NEW_VERSION}" > version.txt  
        echo "Updated version.txt to new version: v${NEW_VERSION}"

  # Step 3: Print the Version to Confirm
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd tic-tac-toe-with-kafka-mongodb/tic-tac-toe
        echo "Final version in version.txt should be:"
        cat version.txt

options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
