substitutions:
  _USER: "Rahul"


steps:
  # Step 1: Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://github.com/rahulrambo9/tic-tac-toe-with-kafka-mongodb.git
        cd tic-tac-toe-with-kafka-mongodb/tic-tac-toe
        echo "Repository cloned and navigated to subdirectory."

  # Step 2: Read and increment the version
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd tic-tac-toe-with-kafka-mongodb/tic-tac-toe
        if [ -f version.txt ]; then
          # Read the current version, ensure it starts with 'v' and strip 'v'
          _CURRENT_VERSION=$(cat version.txt | sed 's/^v//')
          echo "Current version in version.txt: v$_CURRENT_VERSION"
        
          # Check if _CURRENT_VERSION is a valid number
          if [[ $_CURRENT_VERSION =~ ^[0-9]+$ ]]; then
            # Increment the version
            _NEW_VERSION=$(( _CURRENT_VERSION + 1 ))
            echo "Updated version: v$_NEW_VERSION"
            # Write the new version back to version.txt with 'v' prefix
            echo "v$_NEW_VERSION" > version.txt  
          else
            echo "Error: Current version is not a valid number"
            exit 1
          fi
        else
          echo "version.txt not found!"
          exit 1
        fi

  # Optional: Print user information
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Hello ${_USER}"
        echo "Your new TagName is v${_NEW_VERSION}"  # Note: This variable is local to the previous step

  # Step 4: Commit and push the updated version.txt back to the repository
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd tic-tac-toe-with-kafka-mongodb/tic-tac-toe
        git config --global user.email "rahulvhd9@gmail.com"
        git config --global user.name "rahulrambo9"
        git add version.txt
        git commit -m "Increment version to v$_NEW_VERSION"  # Using the new version directly
        git push origin main  # Make sure your branch name is correct   

options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY  # Use this logging option to avoid the error

# Optional: Specify a timeout
timeout: '1200s'  # Adjust the timeout as needed
