substitutions:
  _USER: "Rahul"

steps:
  # Step 1: Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://github.com/rahulrambo9/tic-tac-toe-with-kafka-mongodb.git
        cd tic-tac-toe-with-kafka-mongodb/tic-tac-toe
        echo "Repository cloned and navigated to subdirectory."

  # Step 2: Read the current version from version.txt
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd tic-tac-toe-with-kafka-mongodb/tic-tac-toe
        if [ -f version.txt ]; then
          CURRENT_VERSION=$(cat version.txt | sed 's/v//')  # Strip the 'v' for incrementing
          echo "Current version in version.txt: v$CURRENT_VERSION"
          NEW_VERSION=$((CURRENT_VERSION + 1))  # Increment version number
          echo "Updated version: v$NEW_VERSION"
          echo "v$NEW_VERSION" > version.txt  # Write new version back to file
        else
          echo "version.txt not found!"
          exit 1
        fi

  # Optional: Print user information
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Hello ${_USER}"
        echo "Your new TagName is v${NEW_VERSION}"

  # Step 4: Commit and push the updated version.txt back to the repository
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd tic-tac-toe-with-kafka-mongodb/tic-tac-toe
        git config --global user.email "rahulvhd9@gmail.com"
        git config --global user.name "rahulrambo9"
        git add version.txt
        git commit -m "Increment version to v${NEW_VERSION}"
        git push origin main  # Make sure your branch name is correct   

options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY  # Use this logging option to avoid the error

# Optional: Specify a timeout
timeout: '1200s'  # Adjust the timeout as needed
