substitutions:
  _USER: "Rahul"
  _TAG_NAME: "v1"

steps:
  # Step 1: Print User Name
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Hello ${_USER}"
  
  # Step 2: Print Tag Name
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Your TagName is ${_TAG_NAME}"

  # Step 3: Clone the Repository
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git config --global user.email "rahulvhd9@gmail.com"
        git config --global user.name "rahulrambo9"
        git clone https://github.com/rahulrambo9/tic-tac-toe-with-kafka-mongodb.git

  # Step 4: Read, Increment, and Display the Version from version.txt in Subdirectory
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd tic-tac-toe-with-kafka-mongodb/tic-tac-toe
        if [ ! -f version.txt ]; then echo "0" > version.txt; fi  # Create version.txt if it doesn't exist
        export _TAG_VERSION=$(($(cat version.txt) + 1))
        echo "${_TAG_VERSION}" > version.txt
        echo "Hello ${_USER}"
        echo "Your new TagName is v${_TAG_VERSION}"

  # Step 5: Commit and Push the Updated version.txt Back to the Repository
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd tic-tac-toe-with-kafka-mongodb/tic-tac-toe
        git add version.txt
        git commit -m "Increment version to v${_TAG_VERSION}"
        git push origin main  # Ensure "main" is your correct branch name

options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY

# Optional: Specify a timeout
timeout: '1200s'
