apiVersion: v1
kind: Service
metadata:
  name: mongo-db-svc
  namespace: mongo
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo-db